name: test

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  Run_test:
    name: Test ElementFunction, DualNumber, and AutoDiff
    runs-on: ubuntu-latest
    steps:
      # Checkout the head of branch  See: https://github.com/actions/checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3 
        with:
          python-version: '3.9' 
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install pytest
          pip install pytest-cov
          pip install pytest-xdist[psutil]
        ## parallel run has the same speed as non-para so far
      - name: Run tests 
        run: |
          cd tests
          pytest -n auto test_ElementFunction.py
          pytest -n auto test_DualNumber.py
          pytest -n auto test_AutoDiff.py
  
        
